- server/db/models/events.js
- server/db/models/groups.js
- server/db/models/index.js
- server/db/models/user.js
closes #2  
Added events and group models
> added groups and events model

- script/seed.js
> Update: Added/Made changes to seed file for users, events, groups

- package-lock.json
- package.json
- script/seed.js
- server/api/users.js
- server/db/models/index.js
added relations to the db for users groups and events, added working examples for seed file to populate the events and groups
> added working relations and improved seed data

- server/api/users.js
Added functionality for posting events to database in backend
---
> Added post route in backend for adding events

- client/store/event.js
> event store

- client/components/EventForm.js
- client/components/NewEvent.js
- client/components/user-home.js
- package-lock.json
- package.json
> Event form

- client/components/CreateGroup.js
> created form component for new group

- client/components/CreateEvent.js
- client/components/UserGroups.js
- client/store/event.js
- client/store/group.js
- script/seed.js
- server/api/users.js
- server/db/models/events.js
- server/db/models/groups.js
- server/db/models/index.js
- server/db/models/user.js
added corrections and coreys comments to work on
> Corrections

- client/components/GroupCard.js
- client/components/UserGroups.js
> Group card component

- client/components/AllEvents.js
- client/components/EventCard.js
> Created AllEvents and Event Card components

- package-lock.json
- server/api/users.js
> created a route to add a new group for a specific user

- client/components/UserGroups.js
- client/components/index.js
fixes usergroup frontend component to properly render
> added working frontend usergroups route

- server/api/groups.js
- server/api/index.js
- server/api/users.js
> created a route to delete a single event

- client/store/group.js
> added delete group thunk and update group store

- client/components/EventCard.js
- client/components/navbar.js
wrapped some routing elements in buttons for ui benefit
> added some buttons ui

- server/api/users.js
> Edit votes put route

- client/components/AllEvents.js
- client/components/CreateEvent.js
- client/components/SingleGroup.js
- client/components/UserGroups.js
- client/routes.js
- client/store/event.js
- client/store/group.js
> Update: Fixed singlegroup/allevents component

- client/components/AllEvents.js
- client/components/EventCard.js
- client/store/event.js
- server/api/users.js
> editing-votes

- client/components/AllEvents.js
- client/components/CreateEvent.js
- client/components/SingleGroup.js
- client/store/event.js
- server/api/users.js
> Create event persist

- client/components/AllEvents.js
- client/components/EventCard.js
- client/store/event.js
- server/api/users.js
> Vote buttons

- server/api/users.js
> Decider route

- client/components/AllEvents.js
- client/components/SingleGroup.js
- client/store/event.js
- server/api/users.js
> Event button #62

- server/api/users.js
> add all groups route

- client/store/event.js
> events stay in order when voting

- client/components/AllEvents.js
> Add event decision timer

- client/components/JoinGroups.js
- client/store/group.js
> Joingroup thunk

- client/store/group.js
- server/api/users.js
> Joingroupbackend

- client/components/CreateEvent.js
- client/components/CreateGroup.js
- client/components/EventCard.js
- client/components/GroupCard.js
- client/components/JoinGroups.js
- client/components/SingleGroup.js
- client/components/UserGroups.js
- client/components/navbar.js
- client/components/user-home.js
- package-lock.json
- package.json
- public/index.html
> Styling semantic ui

- server/api/users.js
- server/db/models/index.js
> Limitvotes

- server/db/models/userEvents.js
> added user events model file that was not commited on the last commit

- client/components/CreateEvent.js
- client/components/PlacesBar.js
- client/components/user-home.js
- package-lock.json
- package.json
> Googleplacesapi

- client/components/AllEvents.js
- package-lock.json
- package.json
- server/api/users.js
- server/index.js
> Node mailer

- client/app.js
- client/components/AllEvents.js
- client/components/CreateEvent.js
- client/components/CreateGroup.js
- client/components/EventCard.js
- client/components/GroupCard.js
- client/components/JoinGroups.js
- client/components/UserGroups.js
- client/components/auth-form.js
- client/components/navbar.js
- public/index.html
- public/style.css
> Css styling

- client/components/AllEvents.js
- client/components/EventCard.js
- client/components/GroupCard.js
- client/components/JoinGroups.js
- client/components/UserGroups.js
- client/components/auth-form.js
- client/components/navbar.js
> decreased border-radius for GroupCard and EventCard

- client/components/AllEvents.js
- client/components/MapCard.js
- script/seed.js
- server/api/users.js
- server/db/models/events.js
> Google map

- client/app.js
- client/components/AllEvents.js
- client/components/CreateEvent.js
- client/components/EventCard.js
- client/components/GroupCard.js
- client/components/JoinGroups.js
- client/components/UserGroups.js
- client/components/navbar.js
- client/components/user-home.js
> New css changes

- client/components/AllEvents.js
- client/components/CreateEvent.js
- client/components/PlacesBar.js
- client/components/auth-form.js
> fixed css errors

- client/components/GroupCard.js
> changed margin on groupcard
